annotation/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<page_num>[0-9]+)/$', views.index, name='index'),
    url(r'^token/default-labels/(?P<token_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^ambiguous/$', views.ambiguous, name='ambiguous'),
    url(r'^ambiguous-detail/(?P<token_id>[0-9]+)/$', views.ambiguous_detail, name='ambiguous-detail'),
    url(r'^occurrence/(?P<occur_id>[0-9]+)/$', views.occurrence,
        name='occurrence'),
    url(r'^tagset/$', views.tagset, name='tagset'),
    url(r'^suggestions/(?P<text_value>.+)/$', views.autocomplete_pos, name='suggestions'),
    url(r'^search/$', views.search, name='search-result'),
]

django_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^annotate/', include('annotation.urls', namespace="annotation")),
    url(r'^gornany/', include('gornany.urls', namespace="gornany")),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

annotation/models.py
from django.db import models

# Create your models here.


class Token(models.Model):
    token_text = models.CharField(max_length=15)
    default_coda = models.CharField(max_length=15, null=True, blank=True)
    default_segmentation = models.CharField(max_length=15, null=True, blank=True)
    default_pos = models.CharField(max_length=15, null=True, blank=True)
    ambiguous = models.BooleanField(default=False)
    freq = models.IntegerField()

    def __unicode__(self):              # __unicode__ on Python 2
        return self.token_text


class Tweet(models.Model):
    tweet_id = models.IntegerField(primary_key=True)
    tweet_text = models.CharField(max_length=140)
    members = models.ManyToManyField(Token, through='TokenOccurrence')

    def __unicode__(self):              # __unicode__ on Python 2
        return self.tweet_text


class TokenOccurrence(models.Model):
    token = models.ForeignKey(Token, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    position = models.PositiveSmallIntegerField(null=False)
    coda = models.CharField(max_length=15,null=True, blank=True)
    segmentation = models.CharField(max_length=15,null=True, blank=True)
    pos = models.CharField(max_length=15,null=True, blank=True)

annotation/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.forms import TextInput
from .models import Token, TokenOccurrence


# class DefaultAnnotationForm(forms.Form):
#     coda = forms.CharField(label='CODA', max_length=15,
#                            widget=forms.TextInput(attrs={'placeholder': 'CODA', 'aria-describedby': 'helpBlock_coda',
#                                                          'class': 'form-control'}))
#     segmentation = forms.CharField(label='Segmentation', max_length=15, widget=forms.TextInput(
#         attrs={'placeholder': 'Segmentation', 'aria-describedby': 'helpBlock_seg',
#                'class': 'form-control'}))
#     pos = forms.CharField(label='POS', max_length=15, widget=forms.TextInput(
#         attrs={'placeholder': 'Part-of-speech', 'aria-describedby': 'helpBlock_pos',
#                'class': 'form-control'}))
#     ambiguity = forms.BooleanField(label=u'ملتبس', initial=False, required=False)
#
#     def process_labels(self):
#         cd = self.cleaned_data
#         print cd

class TokenForm(forms.ModelForm):
    class Meta:
        model = Token
        fields = ['default_coda', 'default_segmentation', 'default_pos', 'ambiguous']
        widgets = {
            'default_pos': TextInput(
                attrs={'autocomplete': 'off', 'spellcheck': 'false', 'id': "suggestionsTB",
                       'class': "typeahead form-control", 'dir': 'rtl'}),
        }


class TokenOccurrenceForm(forms.ModelForm):
    class Meta:
        model = TokenOccurrence
        fields = ['coda', 'segmentation', 'pos']
        widgets = {
            'coda': TextInput(
                attrs={'class': "form-control", 'dir': 'rtl'}),
            'segmentation': TextInput(
                attrs={'class': "form-control", 'dir': 'rtl'}),
            'pos': TextInput(
                attrs={'autocomplete': 'off', 'spellcheck': 'false', 'id': "suggestionsTB",
                       'class': "typeahead form-control", 'dir': 'rtl'}),

        }

annotation/views.py
# -*- coding:utf-8 -*-
import json
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Token, Tweet, TokenOccurrence
from .forms import TokenForm, TokenOccurrenceForm

# Create your views here.
pos_tagset = [u'ترقيم', u'عدد', u'أجنبي', u'اسم', u'فعل', u'صفة', u'أداة', u'جر', u'ضمير', u'تعريف', u'عطف', u'لاحق',
              u'اختصار', u'رابط', u'شعور', u'وسم', u'مرجع']


def index(request, page_num):
    p = int(page_num)
    most_common_tokens = Token.objects.order_by('-freq')[(p * 10) - 10:p * 10]

    context = {'most_common_tokens': most_common_tokens, 'page': p}
    return render(request, 'annotation/index.html', context)


def detail(request, token_id):
    token = get_object_or_404(Token, pk=token_id)
    # occurrences = token.tweet_set.all()
    tweet_occurPosition_list = list()
    # for tweet in occurrences:
    token_occur_QuerySet = TokenOccurrence.objects.filter(token=token)
    for occur in token_occur_QuerySet:
        tweet_occurPosition_list.append((occur.tweet.tweet_text, occur.position))

    if request.method == 'POST':
        form = TokenForm(request.POST, instance=token)
        if form.is_valid():
            form.save()
            return render(request, 'annotation/detail.html', {'token': token, 'occurrences': tweet_occurPosition_list})
    else:
        form = TokenForm(instance=token)

    return render(request, 'annotation/detail.html',
                  {'token': token, 'occurrences': tweet_occurPosition_list, 'form': form})


def ambiguous(request):
    ambiguous_tokens = Token.objects.filter(ambiguous=True)
    context = {'ambiguous_tokens': ambiguous_tokens}
    return render(request, 'annotation/ambiguous.html', context)


def ambiguous_detail(request, token_id):
    token = get_object_or_404(Token, pk=token_id)
    tweet_occurPosition_list = list()
    token_occur_QuerySet = TokenOccurrence.objects.filter(token=token)

    for occur in token_occur_QuerySet:
        tweet_occurPosition_list.append((occur.tweet, occur.position, occur.id))
    return render(request, 'annotation/ambiguous_detail.html',
                  {'token': token, 'occurrences': tweet_occurPosition_list})


def occurrence(request, occur_id):
    occur = get_object_or_404(TokenOccurrence, pk=occur_id)

    if request.method == 'POST':
        form = TokenOccurrenceForm(request.POST, instance=occur)
        if form.is_valid():
            form.save()
            tweet_occurPosition_list = list()
            token_occur_QuerySet = TokenOccurrence.objects.filter(token=occur.token)
            for occur in token_occur_QuerySet:
                tweet_occurPosition_list.append((occur.tweet, occur.position, occur.id))
            return render(request, 'annotation/ambiguous_detail.html',
                          {'token': occur.token, 'occurrences': tweet_occurPosition_list, 'saved': True})
    else:
        form = TokenOccurrenceForm(instance=occur)

    context = {'occurrence': occur, 'form': form}
    return render(request, 'annotation/occur_update.html', context)


def autocomplete_pos(request, text_value):

    tags = text_value.strip().split('+')
    hints = list()
    suggestions = list()
    for tag in tags[:-1]:
        tag = tag.strip()
        if tag not in pos_tagset:
            hints.append(u'إن الوسم %s غير موجود ضمن القائمة المسموح بإستخدامها' % tag)
    else:
        if tags[-1] not in pos_tagset:
            for pos_tag in pos_tagset:
                if pos_tag.startswith(tags[-1]):
                    suggestions.append(pos_tag)
            else:
                if not suggestions:
                    hints.append(u'إن الوسم %s غير موجود ضمن القائمة المسموح بإستخدامها' % tags[-1])

    print

    return render(request, 'annotation/suggestions.html', {'suggestions':json.dumps(suggestions)})


def search(request):
    if request.method == 'POST':
        querySet = Token.objects.filter(token_text__contains=request.POST['query'])
        print len(querySet)
        return render(request, 'annotation/search_result.html',
                          {'result': querySet})
    else:
        pass

def tagset(request):
    return render(request, 'annotation/tagset.html')

annotation/templates/annotation/ambiguous.html
{% extends 'annotation/base.html' %}
{% block revision %}
    <li class="active"><a href="#"> الكلمات الملتبسة</a></li>
{% endblock revision %}
{% block content %}
    <div class="container">
        <form method="post" action="index.html">
            <div class="row">
                <div class="col-md-12 ">
                    {% if ambiguous_tokens %}
                        <div id="words" name="words" class="table-responsive"
                             style="overflow-y: auto; padding: 10px; height: 889px; visibility: visible;">
                            <table class="table table-condensed table table-hover"
                                   style="direction:rtl;font-size: x-large;">
                                <thead>
                                <tr>
                                    <td>رقم</td>
                                    <td>الكلمة</td>
                                    <td>قسم الكلام</td>
                                    <td>الكتابة الاصطلاحية</td>
                                    <td>التقطيع</td>
                                    <td>التكرار</td>
                                </tr>
                                </thead>
                                <tbody>
                                {% for token in ambiguous_tokens %}
                                    <tr class='clickable-row'
                                        data-href="{% url 'annotation:ambiguous-detail' token.id %}">
                                        <td>{{ token.id }}</td>
                                        <td>{{ token.token_text }}</td>
                                        {% if token.default_pos %}
                                            <td> {{ token.default_pos }}</td>
                                        {% else %}
                                            {# <td class=text-success><span class="glyphicon glyphicon-ok" aria-hidden=true></span> Supported</td> #}
                                            <td class=text-danger><span
                                                    class="glyphicon glyphicon-remove" aria-hidden=true></span></td>
                                        {% endif %}
                                        {% if token.default_coda %}
                                            <td>{{ token.default_coda }}</td>
                                        {% else %}
                                            <td class=text-danger><span
                                                    class="glyphicon glyphicon-remove" aria-hidden=true></span></td>
                                        {% endif %}
                                        {% if token.default_segmentation %}
                                            <td>{{ token.default_segmentation }}</td>
                                        {% else %}
                                            <td class=text-danger><span
                                                    class="glyphicon glyphicon-remove" aria-hidden=true></span></td>
                                        {% endif %}
                                        <td><span class="badge">{{ token.freq }}</span></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        nothing
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

annotation/templates/annotation/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="annotation, NLP, Arabic, ALT, QCRI">
    <meta name="author" content="QCRI/ALT - disooqi">
    {#    <link rel="icon" href="http://getbootstrap.com/favicon.ico">#}

    <title>{% block title %}QCRI/ALT Dialectal Arabic Annotation Project{% endblock title %}</title>


    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'annotation/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'annotation/sticky-footer-navbar.css' %}" rel="stylesheet">


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static 'annotation/ie8-responsive-file-warning.js' %}"></script><![endif]-->
    <script src="{% static 'annotation/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="{% static 'annotation/typeahead.css' %}">


</head>

<body>

<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Dialectal Arabic Annotation</a>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% block unigrams %}
                    <li><a href="{% url 'annotation:index' 1 %}">كل الكلمات</a></li>{% endblock unigrams %}
                {% block revision %}
                    <li><a href="{% url 'annotation:ambiguous' %}"> الكلمات الملتبسة</a></li>{% endblock revision %}
                {% block tagset %}
                    <li><a href="{% url 'annotation:tagset' %}">أقسام الكلام</a></li>{% endblock tagset %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">أدوات <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">حفظ الملف الموسوم</a></li>
                        <li><a href="#">وسم ملف جديد</a></li>
                        <li><a href="#">حذف كلمات</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">تقارير</li>
                        <li><a href="#">عدد الكلمات الموسومة</a></li>
                        <li><a href="#">عدد الكلمات الملتبسة</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" method="post" action="{% url 'annotation:search-result' %}">
                {% csrf_token %}
            {{ form.non_field_errors }}
                <div class="form-group" style="direction: rtl;">
                    <input type="text" id="search-input" name="query"  class="form-control" placeholder="الكلمة المراد البحث عنها">
                </div>
                <button type="submit" class="btn btn-default" onclick="return empty();">بحث</button>
            </form>
        </div><!--/.nav-collapse -->

        {% block default-data %}

        {% endblock default-data %}
    </div>
</nav>

<!-- Begin page content -->
{% block content %}

{% endblock content %}
<footer class="footer">
    <div class="container">
        <p class="text-muted">Copyright &copy;2017 All rights reserved to Qatar Computing Research Institute and
            HBKU</p>
        <p class="text-muted">Designed by ALT - Arabic NLP Team/QCRI</p>
    </div>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{#    <script src="{% static 'annotation/jquery.js' %}"></script>#}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{#<script>window.jQuery || document.write('<script src="{% static 'annotation/jquery.min.js' %}"><\/script>')</script>#}

{#    <script src="{% static 'annotation/bootstrap.js' %}"></script>#}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'annotation/ie10-viewport-bug-workaround.js' %}"></script>
<script src="{% static 'annotation/typeahead.bundle.js' %}"></script>
<script type="text/javascript">
    var arabicPhrases = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.whitespace,
        queryTokenizer: Bloodhound.tokenizers.whitespace,

        remote: {
            url: '{% url "annotation:suggestions" "QUERY"  %}',
            wildcard: 'QUERY'
        }
    });

    $('#rtl-support .typeahead').typeahead({
                hint: false
            },
            {
                name: 'arabic-phrases',
                source: arabicPhrases
            });
</script>
<script>
    jQuery(document).ready(function ($) {
        $(".clickable-row").click(function () {
            window.location = $(this).data("href");
        });
    });
</script>
<script>
    function empty() {
        var x;
        x = document.getElementById("search-input").value;
        if (x == "") {
            alert("أدخل كلمة للبحث");
            return false;
        };
    }
</script>
</body>
</html>

annotation/templates/annotation/index.html
{% extends 'annotation/base.html' %}
{% block unigrams %}<li class="active"><a href="#">كل الكلمات</a></li> {% endblock unigrams %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>QCRI/ALT Dialectal Arabic Annotation Project</h1>
        </div>
{#        <p class="lead"> {% lorem %}</p>#}
        <form method="post" action="index.html">
            <div class="row">
                <div class="col-md-12 ">
                    {% if most_common_tokens %}
                        <div id="words" name="words" class="table-responsive"
                             style="overflow-y: auto; padding: 10px; height: 550px; visibility: visible;">
                            <table class="table table-condensed table table-hover"
                                   style="direction:rtl;font-size: x-large;">
                                <thead>
                                <tr>
                                    <td>رقم</td>
                                    <td>الكلمة</td>
                                    <td>قسم الكلام</td>
                                    <td>الكتابة الاصطلاحية</td>
                                    <td>التقطيع</td>
                                    <td>التكرار</td>
                                </tr>
                                </thead>
                                <tbody>
                                {% for token in most_common_tokens %}
                                    <tr class='clickable-row' data-href="{% url 'annotation:detail' token.id %}">
                                        <td>{{ token.id }}</td>
                                        <td>{{ token.token_text }}</td>
                                        {% if token.default_pos %}
                                            <td> {{ token.default_pos }}</td>
                                        {% else %}
                                            {# <td class=text-success><span class="glyphicon glyphicon-ok" aria-hidden=true></span> Supported</td> #}
                                            <td class=text-danger><span
                                                    class="glyphicon glyphicon-remove" aria-hidden=true></span></td>
                                        {% endif %}
                                        {% if token.default_coda %}
                                            <td>{{ token.default_coda }}</td>
                                        {% else %}
                                            <td class=text-danger><span
                                                    class="glyphicon glyphicon-remove" aria-hidden=true></span></td>
                                        {% endif %}
                                        {% if token.default_segmentation %}
                                            <td>{{ token.default_segmentation }}</td>
                                        {% else %}
                                            <td class=text-danger><span
                                                    class="glyphicon glyphicon-remove" aria-hidden=true></span></td>
                                        {% endif %}
                                        <td><span class="badge">{{ token.freq }}</span></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        nothing
                    {% endif %}
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <nav aria-label="...">
                    <ul class="pagination pagination-lg">
                        {% if page == 1 %}
                            <li class="disabled"><a href="#" aria-label="Previous"><span
                                    aria-hidden="true">&laquo;</span></a></li>
                            <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'annotation:index' page|add:"-1" %}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            <li class="page-item"><a class="page-link"
                                                     href="{% url 'annotation:index' page|add:"-1" %}">{{ page|add:"-1" }} </a>
                            </li>
                            <li class="active"><a href="{% url 'annotation:index' page %}">{{ page }} <span
                                    class="sr-only">(current)</span></a></li>
                            {#                        <li class="page-item"><a class="page-link" href="{% url 'annotation:index' page %}">{{ page }}</a></li>#}
                            </li>
                        {% endif %}
                        <li class="page-item"><a class="page-link"
                                                 href="{% url 'annotation:index' page|add:"1" %}"> {{ page|add:"1" }} </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="{% url 'annotation:index' page|add:"1" %}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock content %}

annotation/templates/annotation/occur_update.html
{% extends 'annotation/base.html' %}
{% load split_string_on_spaces %}
{% block menu %}
    <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'annotation:index' 1 %}">Unigrams</a></li>
            <li><a href="{% url 'annotation:ambiguous' %}">Revision</a></li>
            <li><a href="#">Tagset</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false">Reports <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                </ul>
            </li>
        </ul>
    </div><!--/.nav-collapse -->
{% endblock menu %}
{% block content %}
    <div class="container">
        <br/><br/><br/><br/>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form class="form-horizontal" method="post"
                      action="{% url 'annotation:occurrence' occurrence.id %}" style="direction: rtl;">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        <label class="col-sm-2 col-md-push-10 control-label">التغريدة</label>
                        <div class="col-sm-10 col-md-pull-2">
                            <p class="form-control-static"
                               style="font-size: x-large;">{{ occurrence.tweet.tweet_text|add_code_tag:occurrence.position }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-md-push-10 control-label">الكلمة</label>
                        <div class="col-sm-10 col-md-pull-2">
                            <p class="form-control-static">{{ occurrence.token.token_text }}</p>
                        </div>
                    </div>


                    <div class="form-group {% if form.coda.errors %}has-error{% endif %}">
                        <label for="{{ form.coda.id_for_label }}" class="col-sm-2 col-md-push-10 control-label">الكتابة الاصطلاحية</label>
                        <div class="col-sm-10 col-md-pull-2">
                            {{ form.coda }}
                            {# <input type="text" class="form-control" id="inputEmail3" placeholder="coda">#}
                            {% if form.coda.errors %}
                                <span id="helpBlock_coda" class="help-block">{{ form.coda.errors }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group {% if form.segmentation.errors %}has-error{% endif %}">
                        <label for="{{ form.segmentation.id_for_label }}"
                               class="col-sm-2 col-md-push-10 control-label">التقطيع</label>
                        <div class="col-sm-10 col-md-pull-2">
                            {{ form.segmentation }}
                            {# <input type="text" class="form-control" id="inputPassword3" placeholder="Segmentation">#}
                            {% if form.segmentation.errors %}
                                <span id="helpBlock_coda" class="help-block">{{ form.segmentation.errors }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div id="rtl-support" class="form-group {% if form.pos.errors %}has-error{% endif %}">
                        <label for="{{ form.pos.id_for_label }}"
                               class="col-sm-2 col-md-push-10 control-label">قسم الكلام</label>
                        <div class="col-sm-10 col-md-pull-2">
                            {{ form.pos }}
                            {#  <input type="text" class="form-control" id="inputPassword3" placeholder="POS">#}
                            {% if form.pos.errors %}
                                <span id="helpBlock_coda" class="help-block">{{ form.pos.errors }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">حفظ</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

annotation/templates/annotation/suggestions.html
{% autoescape off %}{{ suggestions }}{% endautoescape %}